k3s_cluster_cidr: '10.60.0.0/16'
cri_socket: /var/run/crio/crio.sock
container_runtime_type: embedded
cni_type: embedded
# k3s_version: v1.22.6+k3s1
k3s_version: v1.23.2+k3s1
k3s_download_url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
# k3s_checksum: sha256:66ecc728f30f3e112324a38b890adb50036af689a63fca41e17b7b6612dff02c
k3s_checksum: sha256:04c4e9760675d7d4844403946f25690dcd8d7dcfa47c4fbbba6c3cfb6cb2f101
pause_image: k8s.gcr.io/pause:3.6
k3s_common_args: >-
  --kubelet-arg cloud-provider=external
  {% if container_runtime_type != 'embedded' %}
  --container-runtime-endpoint "{{ cri_socket }}"
  {% endif %}
  {% if cni_type != 'embedded' %}
  --no-flannel
  {% else %}
  --flannel-iface enp7s0
  {% endif %}
  --pause-image "{{ pause_image }}"
