---
- name: download k3s binary
  get_url:
    url: "{{ k3s_download_url }}"
    checksum: "{{ k3s_checksum }}"
    dest: /usr/local/bin/k3s
    mode: "0755"
  register: k3s_binary

- name: create symlinks
  file:
    state: link
    src: /usr/local/bin/k3s
    path: /usr/local/bin/{{ item }}
  loop:
    - kubectl

- name: make sure /etc/rancher/k3s exists
  file:
    path: /etc/rancher/k3s
    state: directory

- name: write registries config file
  when: registries_config|length
  copy:
    content: "{{ registries_config }}"
    dest: /etc/rancher/k3s/registries.yaml
    mode: "0600"
  register: k3s_registries_config
