---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: csi-attacher
          args:
            - --v=2
        - name: csi-resizer
          args:
          - --v=2
        - name: csi-provisioner
          args:
            - --feature-gates=Topology=true
            - --default-fstype=ext4
            - --v=2
        - name: hcloud-csi-driver
          image: hetznercloud/hcloud-csi-driver:1.6.0
          env:
          - name: LOG_LEVEL
            value: warn
