---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: csi-attacher
          args:
            - --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
            - --v=2
        - name: csi-resizer
          args:
          - --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
          - --v=2
        - name: csi-provisioner
          args:
            - --provisioner=csi.hetzner.cloud
            - --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
            - --feature-gates=Topology=true
            - --v=2
        - name: hcloud-csi-driver
          image: hetznercloud/hcloud-csi-driver:1.5.1
          env:
          - name: LOG_LEVEL
            value: warn
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v2.0.0
