---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: hcloud-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: csi-node-driver-registrar
          args:
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.hetzner.cloud/socket
            - --v=2
        - name: hcloud-csi-driver
          image: hetznercloud/hcloud-csi-driver:1.6.0
          env:
            - name: LOG_LEVEL
              value: warn
