---
- name: install haproxy
  apt:
    name: haproxy
    state: present
  register: haproxy_package

- name: upgrade haproxy
  apt:
    name: haproxy
    state: latest
  register: haproxy_upgrade

- name: create haproxy config
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  register: haproxy_config

- name: start haproxy
  systemd:
    name: haproxy
    daemon_reload: yes
    enabled: yes
    state: "{{ 'restarted' if haproxy_package.changed else ('reloaded' if (haproxy_config.changed or haproxy_upgrade.changed) else 'started') }}"
