---
- name: template MetalLB config
  template:
    src: templates/metallb-config.yaml.j2
    dest: /tmp/kube-manifests/metallb/config.yaml

- name: apply MetalLB manifest
  command: kubectl apply -k /tmp/kube-manifests/metallb

- name: template IP floater config
  template:
    src: templates/floater-config.yaml.j2
    dest: /tmp/kube-manifests/hcloud-ip-floater/secret.yaml

- name: apply hcloud-metallb-floater manifest
  command: kubectl apply -k /tmp/kube-manifests/hcloud-ip-floater
