---
- name: create k3s systemd service unit
  vars:
    k3s_server_args: |-
      --advertise-address {{ private_ip }} \
      --cluster-cidr {{ k3s_cluster_cidr }} \
      --service-cidr {{ k3s_service_cidr }} \
      --cluster-dns {{ k3s_cluster_dns }} \
      --tls-san {{ private_ip }} \
      --tls-san {{ public_ip }} \
      {% if master_external_hostname|length %}
      --tls-san {{ master_external_hostname }} \
      {% endif %}
      {{ k3s_default_server_args }}
  template:
    src: templates/k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  register: k3s_unit

- name: start k3s server
  systemd:
    name: k3s
    daemon_reload: yes
    enabled: yes
    state: "{{ 'restarted' if (k3s_binary.changed or k3s_unit.changed) else 'started' }}"
