---
- name: download k3s binary
  get_url:
    url: "{{ k3s_download_url }}"
    checksum: "{{ k3s_checksum }}"
    dest: /usr/local/bin/k3s
    mode: "0755"
  register: k3s_binary

- name: create symlinks
  file:
    state: link
    src: /usr/local/bin/k3s
    path: /usr/local/bin/{{ item }}
  loop:
    - kubectl
