---
- name: make sure /etc/rancher/k3s exists
  file:
    path: /etc/rancher/k3s
    state: directory

- name: write cluster join token
  copy:
    content: "{{ k3s_ha_master_join_token }}"
    dest: /etc/rancher/k3s/cluster-token
    mode: "0600"
