---
# FIXME: this breaks kube-proxy until first config refresh ...
- name: reload iptables rules
  systemd:
    name: iptables
    state: restarted
    enabled: yes

- name: restart networkd
  systemd:
    name: systemd-networkd
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
