k3s_service_cidr: '10.61.0.0/16'
k3s_cluster_dns: '10.61.0.10'
k3s_ha_enabled: no
k3s_ha_master_join_token: "token"
k3s_advertise_address: "{{ private_ip }}"
k3s_advertise_port: "6443"
k3s_listen_port: "6443"
k3s_loadbalancer_address: ""
k3s_external_address: ""
use_hetzner_loadbalancers: no
k3s_default_server_args: >-
  --disable-cloud-controller
  {% if cni_type != 'embedded' %}
  --disable-network-policy
  --flannel-backend none
  {% else %}
  --flannel-backend host-gw
  {% endif %}
  --node-taint "node-role.kubernetes.io/master:NoSchedule"
  --kube-apiserver-arg "service-node-port-range=1-32767"
  --disable servicelb
  --disable traefik
  {% if k3s_ha_enabled %}
  --token-file /etc/rancher/k3s/cluster-token
  {% endif %}

